@startuml PST STAT Client using SmrbSegmentProducer sequence
actor Client
Client -> StatApplicationManager: configure beam
activate StatApplicationManager
StatApplicationManager -> SmrbSegmentProducer: SmrbSegmentProducer(data_key, weights_key, viewer)
activate SmrbSegmentProducer
Client -> StatApplicationManager: configure scan
StatApplicationManager -> SmrbSegmentProducer: connect
StatApplicationManager <-- SmrbSegmentProducer: connected
StatApplicationManager -> StatProcessor: StatProcessor(config)
activate StatProcessor
StatApplicationManager <-- StatProcessor: configured
Client <-- StatApplicationManager: scan configured
group scan
  Client -> StatApplicationManager: start scan
  StatApplicationManager -> StatApplicationManager: start background processing
  loop in background while scanning
      StatApplicationManager -> SmrbSegmentProducer: next_segment()
      StatApplicationManager <-- SmrbSegmentProducer: return segment
      StatApplicationManager -> StatProcessor: process(segment)
      StatApplicationManager <-- StatProcessor
      StatApplicationManager -> StatApplicationManager: wait stat interval
  end
  Client -> StatApplicationManager: end scan
  StatApplicationManager -> StatApplicationManager: stop background processing
end
Client -> StatApplicationManager: deconfigure scan
StatApplicationManager --> StatProcessor: drop
deactivate StatProcessor
Client <-- StatApplicationManager: scan deconfigured
Client -> StatApplicationManager: deconfigure beam
StatApplicationManager -> SmrbSegmentProducer: disconnect
deactivate SmrbSegmentProducer
Client <-- StatApplicationManager: beam deconfigured
@enduml