@startuml PST STAT Client using datablock sequence
actor Client
Client -> StatApplicationManager: configure beam
activate StatApplicationManager
StatApplicationManager -> "Data RB Viewer": connect
activate "Data RB Viewer"
StatApplicationManager -> "Weights RB Viewer": connect
activate "Weights RB Viewer"
Client -> StatApplicationManager: configure scan
StatApplicationManager -> StatProcessor: StatProcessor(config)
activate StatProcessor
StatApplicationManager <-- StatProcessor: configured
Client <-- StatApplicationManager: scan configured
group scan
  Client -> StatApplicationManager: start scan
  StatApplicationManager -> StatApplicationManager: start background processing
  StatApplicationManager -> "Data RB Viewer": get data header
  StatApplicationManager -> "Weights RB Viewer": get weights header
  StatApplicationManager -> StatApplicationManager: validate headers against config
  loop in background while scanning
      StatApplicationManager -> "Data RB Viewer": get next block
      StatApplicationManager <-- "Data RB Viewer": return block_ptr
      StatApplicationManager -> "Weights RB Viewer": get weights for data
      StatApplicationManager <-- "Weights RB Viewer": return weights_ptr
      StatApplicationManager -> StatProcessor: process(block_ptr, block_length, weights_ptr, weights_length)
      StatApplicationManager <-- StatProcessor
      StatApplicationManager -> StatApplicationManager: wait stat interval
  end
  Client -> StatApplicationManager: end scan
  StatApplicationManager -> StatApplicationManager: stop background processing
end
Client -> StatApplicationManager: deconfigure scan
StatApplicationManager --> StatProcessor: drop
deactivate StatProcessor
Client <-- StatApplicationManager: scan deconfigured
Client -> StatApplicationManager: deconfigure beam
StatApplicationManager -> "Data RB Viewer": disconnect
deactivate "Data RB Viewer"
StatApplicationManager -> "Weights RB Viewer": disconnect
deactivate "Weights RB Viewer"
Client <-- StatApplicationManager: beam deconfigured
@enduml