@startuml PST Stat Class Diagram
allow_mixing

package ska::pst::common {
  class ApplicationManager <<abstract>>

}
package ska::pst::smrb {
  class DataBlockView
}

class StatApplicationManager {
  + StatApplicationManager()
  + ~StatApplicationManager()
  + perform_configure_beam(config: AsciiHeader)
  + perform_configure_scan(config: AsciiHeader)
  + perform_start_scan()
  + perform_scan()
  + perform_end_scan()
  + perform_deconfigure_scan()
  + perform_deconfigure_beam()
  - processor: StatProcessor
  - data_rb_view: DataBlockView
  - weights_rb_view: DataBlockView
}

class FileProcessor {
  + FileProcessor(config: AsciiHeader)
  + ~FileProcessor()
  + process()
  - reader: DataWeightFileBlockLoader
  - processor: StatProcessor
}

class DataWeightFileBlockLoader {
  + DataWeightFileBlockLoader(data_file, weights_file)
  + ~DataWeightFileBlockLoader()
  + next_block(): (block_ptr: char*, weights_ptr: char*)
}

class StatProcessor {
  + StatProcessor(data_config: AsciiHeader, weights_config: AsciiHeader)
  + ~StatProcessor()
  + process(block_ptr: char*, block_length: usize_t, weights_ptr: char*, weights_length: usize_t)
  - storage: std::shared_ptr<StatStorage>
  - computer: std::unique_ptr<StatComputer>
  - writer: std::unique_ptr<StatPublisher>
  - config: AsciiHeader
}

class StatComputer {
  + StatComputer(config: AsciiHeader, std::shared_ptr<StatStorage> storage)
  + ~StatComputer()
  + compute(block_ptr: char*, block_length: usize_t, weights_ptr: char*, weights_length: usize_t)
  - storage: std::shared_ptr<StatStorage>
  - config: AsciiHeader
}

class StatStorage {
  + StatStorage(config: AsciiHeader)
  + resize(uint32_t ntime_bins, uint32_t nfreq_bins)
  + reset()
  + uint32_t get_npol()
  + uint32_t get_ndim()
  + uint32_t get_nchan()
  + uint32_t get_nbin()
  + uint32_t get_nrebin()
  + uint32_t get_ntime_bins()
  + uint32_t get_nfreq_bins()
  + uint32_t get_ntime_vals()
  + bool is_storage_resized()
  + bool is_storage_reset()
  + mean_frequency_avg: std::vector<std::vector<float>>
  + mean_frequency_avg_masked: std::vector<std::vector<float>>
  + variance_frequency_avg: std::vector<std::vector<float>>
  + variance_frequency_avg_masked: std::vector<std::vector<float>>
  + mean_spectrum: std::vector<std::vector<std::vector<float>>>
  + variance_spectrum: std::vector<std::vector<std::vector<float>>>
  + mean_spectral_power: std::vector<std::vector<float>>
  + maximum_spectral_power: std::vector<std::vector<float>>
  + histogram_1d_freq_avg: std::vector<std::vector<std::vector<uint32_t>>>
  + histogram_1d_freq_avg_masked: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_2d_freq_avg: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_2d_freq_avg_masked: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_1d_freq_avg: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_1d_freq_avg_masked: std::vector<std::vector<std::vector<uint32_t>>>
  + num_clipped_samples_spectrum: std::vector<std::vector<std::vector<uint32_t>>>
  + num_clipped_samples: std::vector<std::vector<uint32_t>>
  + spectrogram: std::vector<std::vector<std::vector<float>>>
  + timeseries: std::vector<std::vector<std::vector<float>>>
  + timeseries_masked: std::vector<std::vector<std::vector<float>>>
  + rfi_mask_lut: std::vector<bool>
}

class StatPublisher <<abstract>> {
  # storage: std::shared_ptr<StatStorage>
  # config: AsciiHeader
  + StatPublisher(config: AsciiHeader, storage: std::shared_ptr<StatStorage>)
  + ~StatPublisher()
  {abstract} + publish()
}

class StatHdf5FileWriter implements StatPublisher {
  + StatHdf5FileWriter(config: AsciiHeader, storage: std::shared_ptr<StatStorage>)
  + ~StatHdf5FileWriter()
  + publish()
}

StatProcessor *-- StatComputer
StatProcessor *-- StatPublisher
StatProcessor o-- StatStorage
StatComputer o-- StatStorage
StatPublisher o-- StatStorage

ApplicationManager <|-- StatApplicationManager
StatApplicationManager o-- DataBlockView
StatApplicationManager *-- StatProcessor

FileProcessor *-- DataWeightFileBlockLoader
FileProcessor *-- StatProcessor

component ska_pst_stat_core
ska_pst_stat_core -- "uses" StatApplicationManager
component ska_pst_stat_file_processor
ska_pst_stat_file_processor -- "uses" FileProcessor

@enduml
