@startuml PST Stat Class Diagram
allow_mixing

package ska::pst::common
{
  class ApplicationManager <<abstract>>
  class FileSegmentProducer
}

package ska::pst::smrb
{
  class SmrbSegmentProducer
}

class StatApplicationManager {
  + StatApplicationManager()
  + ~StatApplicationManager()
  + perform_configure_beam(config: AsciiHeader)
  + perform_configure_scan(config: AsciiHeader)
  + perform_start_scan()
  + perform_scan()
  + perform_end_scan()
  + perform_deconfigure_scan()
  + perform_deconfigure_beam()
  + set_timeout()
  - processor: std::unique_ptr<StatProcessor>
  - producer: std::shared_ptr<SmrbSegmentProducer>
}

class FileProcessor {
  + FileProcessor(config: AsciiHeader)
  + ~FileProcessor()
  + process()
  - processor: std::shared_ptr<StatProcessor>
  - reader: std::unique_ptr<FileSegmentProducer>
}

class StatProcessor {
  + StatProcessor(data_config: AsciiHeader, weights_config: AsciiHeader)
  + ~StatProcessor()
  + add_publisher(std::unique_ptr<StatPublisher>)
  + bool validate_segment(segment: SegmentProducer::Segment)
  + bool process(segment: SegmentProducer::Segment)
  + interrupt()
  - storage: std::shared_ptr<StatStorage>
  - computer: std::unique_ptr<StatComputer>
  - publishers: std::vector<std::unique_ptr<StatPublisher>>
  - config: AsciiHeader
}

class StatComputer {
  + StatComputer(data_config: AsciiHeader, weights_config: AsciiHeader, storage: StatStorage)
  + ~StatComputer()
  + bool compute(segment: SegmentProducer::Segment)
  + initialise()
  + interrupt()
  - storage: std::shared_ptr<StatStorage>
  - config: AsciiHeader
}

class StatStorage {
  + StatStorage(config: AsciiHeader)
  + resize(uint32_t ntime_bins, uint32_t nfreq_bins)
  + reset()
  + uint32_t get_npol() const
  + uint32_t get_ndim() const
  + uint32_t get_nchan() const
  + uint32_t get_nbin() const
  + uint32_t get_nrebin() const
  + uint32_t get_ntime_bins() const
  + uint32_t get_nfreq_bins() const
  + uint32_t get_ntime_vals() const
  + double get_total_sample_time() const
  + void set_total_sample_time(double)
  + bool is_storage_resized() const
  + bool is_storage_reset() const
  + mean_frequency_avg: std::vector<std::vector<float>>
  + mean_frequency_avg_rfi_excised: std::vector<std::vector<float>>
  + variance_frequency_avg: std::vector<std::vector<float>>
  + variance_frequency_avg_rfi_excised: std::vector<std::vector<float>>
  + mean_spectrum: std::vector<std::vector<std::vector<float>>>
  + variance_spectrum: std::vector<std::vector<std::vector<float>>>
  + mean_spectral_power: std::vector<std::vector<float>>
  + maximum_spectral_power: std::vector<std::vector<float>>
  + histogram_1d_freq_avg: std::vector<std::vector<std::vector<uint32_t>>>
  + histogram_1d_freq_avg_rfi_excised: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_2d_freq_avg: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_2d_freq_avg_rfi_excised: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_1d_freq_avg: std::vector<std::vector<std::vector<uint32_t>>>
  + rebinned_histogram_1d_freq_avg_rfi_excised: std::vector<std::vector<std::vector<uint32_t>>>
  + num_clipped_samples_spectrum: std::vector<std::vector<std::vector<uint32_t>>>
  + num_clipped_samples: std::vector<std::vector<uint32_t>>
  + num_clipped_samples_rfi_excised: std::vector<std::vector<uint32_t>>
  + spectrogram: std::vector<std::vector<std::vector<float>>>
  + timeseries: std::vector<std::vector<std::vector<float>>>
  + timeseries_rfi_excised: std::vector<std::vector<std::vector<float>>>
  + rfi_mask_lut: std::vector<bool>
  + scalar_stats_t : struct
}

class StatPublisher <<abstract>> {
  # config: AsciiHeader
  + StatPublisher(config: AsciiHeader)
  + ~StatPublisher()
  {abstract} + publish(std::shared_ptr<StatStorage>)
}

class ScalarStatPublisher implements StatPublisher {
  + ScalarStatPublisher(config: AsciiHeader)
  + ~ScalarStatPublisher()
  + publish(std::shared_ptr<StatStorage>)
  + reset()
  + scalar_stats_t get_scalar_stats();
}

class StatHdf5FileWriter implements StatPublisher {
  + StatHdf5FileWriter(config: AsciiHeader)
  + ~StatHdf5FileWriter()
  + publish(std::shared_ptr<StatStorage>)
}

StatProcessor *-- StatComputer
StatProcessor *-- StatPublisher
StatProcessor o-- StatStorage
StatComputer o-- StatStorage
StatPublisher o-- StatStorage

ApplicationManager <|-- StatApplicationManager
StatApplicationManager o-- SmrbSegmentProducer
StatApplicationManager *-- StatProcessor

FileProcessor *-- StatProcessor
FileProcessor o- FileSegmentProducer

component ska_pst_stat_core
ska_pst_stat_core -- "uses" StatApplicationManager
component ska_pst_stat_file_processor
ska_pst_stat_file_processor -- "uses" FileProcessor

@enduml
