@startuml PST STAT DADA file processor
actor Client
Client -> FileProcessor: create(config)
activate FileProcessor
FileProcessor -> StatProcessor: StatProcessor(config)
activate StatProcessor
Client -> FileProcessor: process(data_file_path, weights_file_path)
FileProcessor -> FileReader: FileReader(file)
activate FileReader
FileReader -> "Data File": mmap
activate "Data File"
FileReader -> "Weights File": mmap
activate "Weights File"

loop for configured number of blocks or EOF
  FileProcessor -> FileReader: next_block()
  FileReader --> "Data File": seek to block
  FileReader --> "Weights File": seek to weights block
  FileProcessor <-- FileReader: (block_ptr, weights_ptr)
  FileProcessor -> StatProcessor: process(block_ptr, block_length, weights_ptr, weights_length)
  FileProcessor <-- StatProcessor
end

FileProcessor --> FileReader: drop
FileReader --> "Data File": release
deactivate "Data File"
FileReader --> "Weights File": release
deactivate "Weights File"
deactivate FileReader

' FileProcessor -> FileReader: create
' activate FileReader
' FileReader -> File: mmap
' activate File
' loop while data present
'   FileProcessor -> FileReader: read next
'   FileProcessor <-- FileReader: return next block ptr or null
'   alt data present
'     FileProcessor -> StatProcessor: process(block_ptr, block_length)
'   else no data preset
'     Client <-- FileProcessor: process complete
'   end
' end

@enduml