@startuml PST STAT DADA file processor
actor Client
Client -> FileProcessor: create(config)
activate FileProcessor
FileProcessor -> StatProcessor: StatProcessor(config)
activate StatProcessor
Client -> FileProcessor: process(data_file_path, weights_file_path)
FileProcessor -> FileSegmentProducer: FileSegmentProducer(file)
activate FileSegmentProducer
FileSegmentProducer -> "Data File": mmap
activate "Data File"
FileSegmentProducer -> "Weights File": mmap
activate "Weights File"

loop for configured number of blocks or EOF
  FileProcessor -> FileSegmentProducer: next_segment()
  FileSegmentProducer --> "Data File": next_block
  FileSegmentProducer --> "Weights File": next_block
  FileProcessor <-- FileSegmentProducer: return segment
  FileProcessor -> StatProcessor: process(segment)
  FileProcessor <-- StatProcessor
end

FileProcessor --> FileSegmentProducer: drop
FileSegmentProducer --> "Data File": release
deactivate "Data File"
FileSegmentProducer --> "Weights File": release
deactivate "Weights File"
deactivate FileSegmentProducer

' FileProcessor -> FileSegmentProducer: create
' activate FileSegmentProducer
' FileSegmentProducer -> File: mmap
' activate File
' loop while data present
'   FileProcessor -> FileSegmentProducer: read next
'   FileProcessor <-- FileSegmentProducer: return next block ptr or null
'   alt data present
'     FileProcessor -> StatProcessor: process(segment)
'   else no data preset
'     Client <-- FileProcessor: process complete
'   end
' end

@enduml
