@startuml PST STAT Processor
actor Client
Client -> StatProcessor: processor = StatProcessor(config)
activate StatProcessor
activate StatComputer
StatProcessor -> StatStorage: storage = StatStorage()
activate StatStorage
StatProcessor -> StatComputer: computer = StatComputer(config, storage)
Client <-- StatProcessor
Client -> StatPublisher : publisher = StatPublisher(config)
activate StatPublisher
Client <-- StatPublisher
Client -> StatProcessor: append(publisher)
loop while has data
  Client -> StatProcessor: process(segment)
  StatProcessor -> StatStorage: reset()
  StatProcessor -> StatComputer: initialise()
  StatProcessor -> StatComputer: process(segment)
  StatComputer --> StatStorage: updates
  StatProcessor <-- StatComputer
  StatProcessor -> StatPublisher: publish(storage)
  StatProcessor <-- StatPublisher
  Client <-- StatProcessor
end
Client --> StatProcessor: drop
deactivate StatProcessor
deactivate StatComputer
deactivate StatPublisher
deactivate StatStorage
@enduml
