oci-image-build:
  needs:
    - dynamic_vars
  dependencies:
    - dynamic_vars
  script:
    - make oci-build-all CAR_OCI_REGISTRY_HOST=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} OCI_BUILD_ADDITIONAL_ARGS=" --build-arg SMRB_RUNTIME_IMAGE=${PST_SMRB_OCI_REGISTRY}/${PST_SMRB_OCI_RUNTIME}:${PST_SMRB_OCI_COMMON_TAG} --build-arg STAT_BUILDER_IMAGE=${PST_SMRB_OCI_REGISTRY}/${PST_SMRB_OCI_BUILDER}:${PST_SMRB_OCI_COMMON_TAG} --build-arg STAT_RUNTIME_IMAGE=${STAT_RUNTIME_IMAGE}"
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /at3.*|skb.*|main/) || (($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /at3.*|skb.*/) && ($CI_PIPELINE_SOURCE == "merge_request_event"))
      variables:
        PST_OCI_COMMON_REGISTRY: ${GITLAB_OCI_COMMON_REGISTRY}
        PST_SMRB_OCI_REGISTRY: ${GITLAB_OCI_SMRB_REGISTRY}
    - if: ($CI_COMMIT_TAG) || ($CI_COMMIT_BRANCH =~ /rel.*|main/) || (($CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /rel.*/) && ($CI_PIPELINE_SOURCE == "merge_request_event"))
      variables:
        PST_OCI_COMMON_REGISTRY: ${SKA_RELEASE_REGISTRY}
        PST_SMRB_OCI_REGISTRY: ${SKA_RELEASE_REGISTRY}

oci-image-publish:
  when: manual